// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3kAn74MtSnRR9Ljk94NDFN6sPGy2RMpg',
    appId: '1:815034401829:web:a1032a4425374f77b5ebcc',
    messagingSenderId: '815034401829',
    projectId: 'chatsite-778a1',
    authDomain: 'chatsite-778a1.firebaseapp.com',
    storageBucket: 'chatsite-778a1.appspot.com',
    measurementId: 'G-B3KX2F73V0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHoaIwHle_Ro4hp8YDDXRQwz1syghi40c',
    appId: '1:815034401829:android:5349e67fa589b473b5ebcc',
    messagingSenderId: '815034401829',
    projectId: 'chatsite-778a1',
    storageBucket: 'chatsite-778a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoiIaNPFVBCmH6ZV40Ji655SFHEeET3no',
    appId: '1:815034401829:ios:da8fc67b7ef36884b5ebcc',
    messagingSenderId: '815034401829',
    projectId: 'chatsite-778a1',
    storageBucket: 'chatsite-778a1.appspot.com',
    iosBundleId: 'com.example.chatSite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoiIaNPFVBCmH6ZV40Ji655SFHEeET3no',
    appId: '1:815034401829:ios:da8fc67b7ef36884b5ebcc',
    messagingSenderId: '815034401829',
    projectId: 'chatsite-778a1',
    storageBucket: 'chatsite-778a1.appspot.com',
    iosBundleId: 'com.example.chatSite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3kAn74MtSnRR9Ljk94NDFN6sPGy2RMpg',
    appId: '1:815034401829:web:ba8ec999837b56adb5ebcc',
    messagingSenderId: '815034401829',
    projectId: 'chatsite-778a1',
    authDomain: 'chatsite-778a1.firebaseapp.com',
    storageBucket: 'chatsite-778a1.appspot.com',
    measurementId: 'G-4TZB85KX6V',
  );
}
